import { LOCKOUT_OPTIONS } from "@/lib/lockouts"

export const TASK_LIMITS = {
  MAX_NAME_LENGTH: 120,
  MAX_DESCRIPTION_LENGTH: 2000,
  MAX_TAG_LENGTH: 100,
  MAX_TAGS_PER_TASK: 100,
  MAX_TASKS_PER_USER: 1000,
  MAX_CHARACTER_NAME_REALM_LENGTH: 100,
} as const

export const TASK_LOCKOUT_OPTIONS = LOCKOUT_OPTIONS
