export const DEFAULT_TAGS = [
    // Races
    "Race: Human", 
    "Race: Dwarf", 
    "Race: Night Elf", 
    "Race: Gnome", 
    "Race: Draenei",
    "Race: Worgen", 
    "Race: Void Elf", 
    "Race: Lightforged Draenei", 
    "Race: Dark Iron Dwarf",
    "Race: Kul Tiran", 
    "Race: Mechagnome",
    "Race: Orc", 
    "Race: Undead", 
    "Race: Tauren", 
    "Race: Troll", 
    "Race: Blood Elf",
    "Race: Goblin", 
    "Race: Nightborne", 
    "Race: Highmountain Tauren", 
    "Race: Mag'har Orc",
    "Race: Zandalari Troll", 
    "Race: Vulpera",
    "Race: Pandaren", 
    "Race: Dracthyr", 
    "Race: Earthen",
    "Race: Haranir",
    // Classes
    "Class: Warrior", 
    "Class: Paladin", 
    "Class: Hunter", 
    "Class: Rogue", 
    "Class: Priest",
    "Class: Death Knight", 
    "Class: Shaman", 
    "Class: Mage", 
    "Class: Warlock", 
    "Class: Monk",
    "Class: Druid", 
    "Class: Demon Hunter", 
    "Class: Evoker",
    // Professions
    "Profession: Alchemy", 
    "Profession: Blacksmithing", 
    "Profession: Enchanting",
    "Profession: Engineering", 
    "Profession: Herbalism", 
    "Profession: Inscription",
    "Profession: Jewelcrafting", 
    "Profession: Leatherworking", 
    "Profession: Mining",
    "Profession: Skinning", 
    "Profession: Tailoring", 
    "Profession: Cooking", 
    "Profession: Fishing",
    // Lockouts
    "Lockout: Daily",
    "Lockout: Weekly",
    "Lockout: No lockout",
    "Lockout: Only once",
    // Content type
    "Raid",
    "Dungeon",
    "PvP",
    // Collection type
    "Transmog",
    "Mount",
    "Pet",
    "Achievement",
    "Toy",
    "Decor",
    "Reputation",
    // Priority
    "Priority: High",
    "Priority: Medium",
    "Priority: Low",
    // Events
    "Event: Darkmoon Faire",
    "Event: Timewalking",
    "Event: Love is in the Air",
    "Event: Hallow's End",
    "Event: Brewfest",
    "Event: Midsummer Fire Festival",
    "Event: Feast of Winter Veil",
] as const

export type ImportantTag = typeof DEFAULT_TAGS[number]
