services:

  curatorsledger:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    restart: unless-stopped
    container_name: curatorsledger-app
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      BATTLENET_CLIENT_ID: ${BATTLENET_CLIENT_ID}
      BATTLENET_CLIENT_SECRET: ${BATTLENET_CLIENT_SECRET}
      BATTLENET_ISSUER: ${BATTLENET_ISSUER}
      AUTH_SECRET: ${NEXTAUTH_SECRET}
      AUTH_URL: ${NEXTAUTH_URL}
      AUTH_TRUST_HOST: ${NEXTAUTH_TRUST_HOST}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - curatorsledger
      - proxy

#  curatorsledger-cleanup:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
#    restart: unless-stopped
#    container_name: curatorsledger-cleanup
#    environment:
#      NODE_ENV: production
#      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
#    command: ["sh", "-c", "while true; do npm run cleanup:expired; sleep 3600; done"]
#    depends_on:
#      postgres:
#        condition: service_healthy
#    networks:
#      - curatorsledger

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - curatorsledger

volumes:
  postgres_data:

networks:
  curatorsledger:
    driver: bridge
  proxy:
    name: proxy
    external: true
