import type { Metadata } from "next";
import { Providers } from "./providers"
import "./globals.css";
import Header from "../components/Header"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: LayoutProps<"/">) {
  return (
    <html
      lang="en"
    >
      <body className="h-screen overflow-hidden flex flex-col">
        <Providers>
          <Header />
          <main className="flex-1 min-h-0 overflow-y-auto">{children}</main>
        </Providers>
      </body>
    </html>
  )
}
